"""
train_unified.py — Master PINO Training Pipeline for Unified Neural-AdS
========================================================================

AdS/CFT Physics Context
------------------------
This script trains a Fourier Neural Operator to learn the holographic map

    Φ_boundary(x)  →  Φ_bulk(x, z)

where ``z`` is the radial (depth) coordinate of Anti-de Sitter space.  The
operator is supervised by *two* objectives:

    L_total  =  L_data  +  λ(epoch) · L_PDE

* **L_data** (MSE):  drives the operator's output toward the ground-truth bulk
  solution generated by the sparse Laplace solver in ``1_generate_physics.py``.
* **L_PDE** (Laplacian residual):  penalises violations of ∇²Φ = 0 in the
  interior of the bulk, enforcing Laplace's equation as a *soft constraint*.
* **λ(epoch)** is ramped from 0 → λ_target by ``PINOScheduler`` so the PDE
  term doesn't destabilise early training when predictions are still random.

Usage
-----
    python train_unified.py                        # defaults
    python train_unified.py --epochs 200 --lr 3e-3 --lambda_target 0.1
    python train_unified.py --help
"""

from __future__ import annotations

import argparse
import os
import time

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

from fno_architectures import FNO2d
from physics_engine import LaplacianLoss, PINOScheduler


# ---------------------------------------------------------------------------
# Argument parser
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Unified Neural-AdS: PINO training pipeline.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    # Data
    p.add_argument("--data_dir", type=str, default="data_holography",
                    help="Directory containing boundary_train.npy & bulk_train.npy")

    # Model
    p.add_argument("--modes", type=int, default=12,
                    help="Number of Fourier modes retained per axis")
    p.add_argument("--width", type=int, default=32,
                    help="Hidden channel width of the FNO")
    p.add_argument("--n_layers", type=int, default=4,
                    help="Number of Fourier layers")

    # Training
    p.add_argument("--epochs", type=int, default=150,
                    help="Total training epochs")
    p.add_argument("--batch_size", type=int, default=64,
                    help="Mini-batch size")
    p.add_argument("--lr", type=float, default=5e-3,
                    help="Peak learning rate for OneCycleLR")
    p.add_argument("--weight_decay", type=float, default=1e-4,
                    help="AdamW weight decay")
    p.add_argument("--grad_clip", type=float, default=0.5,
                    help="Max gradient norm for clipping")

    # PINO
    p.add_argument("--lambda_target", type=float, default=0.1,
                    help="Asymptotic PDE-loss weight λ")
    p.add_argument("--ramp_epochs", type=int, default=50,
                    help="Epochs over which to ramp λ from 0 → target")
    p.add_argument("--ramp_strategy", type=str, default="linear",
                    choices=["linear", "cosine"],
                    help="λ ramp-up curve shape")

    # I/O
    p.add_argument("--save_dir", type=str, default="models",
                    help="Directory for checkpoints")
    p.add_argument("--save_every", type=int, default=50,
                    help="Save a checkpoint every N epochs")

    return p.parse_args()


# ---------------------------------------------------------------------------
# Data preparation
# ---------------------------------------------------------------------------

def load_data(
    data_dir: str,
    grid_size: int = 64,
) -> tuple[torch.Tensor, torch.Tensor, dict]:
    """Load, normalise, and reshape training data.

    The raw boundary array has shape ``(N, grid_size)``; we construct a 2-channel
    input tensor ``(N, 2, H, W)`` where:
        * channel 0 = boundary wave tiled across columns
        * channel 1 = normalised Y-depth coordinate (0 at boundary → 1 at bulk)

    Returns
    -------
    x_train : ``(N, 2, H, W)``
    y_train : ``(N, 1, H, W)``
    norm_stats : dict with keys ``x_mean, x_std, y_mean, y_std``
    """
    x_raw = np.load(os.path.join(data_dir, "boundary_train.npy")).astype(np.float32)
    y_raw = np.load(os.path.join(data_dir, "bulk_train.npy")).astype(np.float32)

    N = x_raw.shape[0]

    # --- Normalisation -------------------------------------------------------
    x_mean, x_std = x_raw.mean(), x_raw.std()
    y_mean, y_std = y_raw.mean(), y_raw.std()
    x_norm = (x_raw - x_mean) / (x_std + 1e-8)
    y_norm = (y_raw - y_mean) / (y_std + 1e-8)

    # --- Channel 0: boundary wave tiled to (N, H, W) -------------------------
    #  x_norm is (N, grid_size) → unsqueeze to (N, 1, grid_size) → tile rows
    wave_2d = np.tile(x_norm[:, np.newaxis, :], (1, grid_size, 1))  # (N, H, W)

    # --- Channel 1: normalised Y-depth coordinate grid -----------------------
    depth_row = np.linspace(0.0, 1.0, grid_size, dtype=np.float32)  # (H,)
    depth_2d = np.tile(
        depth_row[np.newaxis, :, np.newaxis], (N, 1, grid_size)
    )  # (N, H, W)

    # --- Stack into (N, 2, H, W) ---------------------------------------------
    x_input = np.stack([wave_2d, depth_2d], axis=1)  # (N, 2, H, W)
    y_input = y_norm[:, np.newaxis, :, :]             # (N, 1, H, W)

    x_train = torch.from_numpy(x_input)
    y_train = torch.from_numpy(y_input)

    norm_stats = dict(x_mean=x_mean, x_std=x_std, y_mean=y_mean, y_std=y_std)
    return x_train, y_train, norm_stats


# ---------------------------------------------------------------------------
# Training loop
# ---------------------------------------------------------------------------

def train(args: argparse.Namespace) -> None:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"🔥 Device: {device}")
    print(f"   λ ramp: 0 → {args.lambda_target} over {args.ramp_epochs} epochs "
          f"({args.ramp_strategy})")

    # ----- data ---------------------------------------------------------------
    x_train, y_train, norm_stats = load_data(args.data_dir)
    print(f"📦 Data loaded — x: {tuple(x_train.shape)}, y: {tuple(y_train.shape)}")

    loader = DataLoader(
        TensorDataset(x_train, y_train),
        batch_size=args.batch_size,
        shuffle=True,
        pin_memory=True,
        drop_last=False,
    )

    # ----- model --------------------------------------------------------------
    model = FNO2d(
        modes1=args.modes,
        modes2=args.modes,
        width=args.width,
        n_layers=args.n_layers,
        in_channels=2,  # wave + depth coordinate
    ).to(device)

    total_params = sum(p.numel() for p in model.parameters())
    print(f"🧠 FNO2d — {total_params:,} parameters")

    # ----- losses & scheduler -------------------------------------------------
    data_criterion = nn.MSELoss()
    pde_criterion = LaplacianLoss(dx=1.0).to(device)
    pino_scheduler = PINOScheduler(
        lambda_target=args.lambda_target,
        ramp_epochs=args.ramp_epochs,
        strategy=args.ramp_strategy,
    )

    # ----- optimiser ----------------------------------------------------------
    optimizer = optim.AdamW(
        model.parameters(), lr=args.lr, weight_decay=args.weight_decay,
    )
    lr_scheduler = optim.lr_scheduler.OneCycleLR(
        optimizer,
        max_lr=args.lr,
        steps_per_epoch=len(loader),
        epochs=args.epochs,
    )

    # ----- checkpoint directory -----------------------------------------------
    os.makedirs(args.save_dir, exist_ok=True)

    # ----- training -----------------------------------------------------------
    print(f"\n{'Epoch':>6} | {'L_data':>10} | {'L_PDE':>10} | {'λ':>8} | "
          f"{'L_total':>10} | {'LR':>10}")
    print("-" * 72)

    for epoch in range(args.epochs):
        model.train()
        lam = pino_scheduler.get_lambda(epoch)

        epoch_data_loss = 0.0
        epoch_pde_loss = 0.0
        n_batches = 0

        for x_batch, y_batch in loader:
            x_batch = x_batch.to(device, non_blocking=True)
            y_batch = y_batch.to(device, non_blocking=True)

            optimizer.zero_grad(set_to_none=True)

            pred = model(x_batch)                  # (B, 1, H, W)

            # ---------- combined loss ----------
            loss_data = data_criterion(pred, y_batch)
            loss_pde = pde_criterion(pred)
            loss_total = loss_data + lam * loss_pde

            loss_total.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=args.grad_clip)
            optimizer.step()
            lr_scheduler.step()

            epoch_data_loss += loss_data.item()
            epoch_pde_loss += loss_pde.item()
            n_batches += 1

        # ----- epoch summary --------------------------------------------------
        avg_data = epoch_data_loss / n_batches
        avg_pde = epoch_pde_loss / n_batches
        avg_total = avg_data + lam * avg_pde
        current_lr = lr_scheduler.get_last_lr()[0]

        print(f"{epoch + 1:>6d} | {avg_data:>10.6f} | {avg_pde:>10.6f} | "
              f"{lam:>8.4f} | {avg_total:>10.6f} | {current_lr:>10.2e}")

        # ----- checkpointing --------------------------------------------------
        if (epoch + 1) % args.save_every == 0:
            ckpt_path = os.path.join(args.save_dir, f"unified_epoch_{epoch + 1}.pth")
            torch.save(model.state_dict(), ckpt_path)
            print(f"   💾 Checkpoint → {ckpt_path}")

    # ----- final save ---------------------------------------------------------
    final_path = os.path.join(args.save_dir, "unified_neural_ads_final.pth")
    torch.save(model.state_dict(), final_path)
    print(f"\n✅ Training complete.  Final model → {final_path}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    train(parse_args())
